overwriteFiles: false
backupFiles: true
excludedFiles: []
includedFiles:
  - '\.php$'
generateOnMake: true
automaticGeneration: true
implementations:
  PhpUnitGen\Core\Contracts\Generators\TestGenerator: PhpUnitGen\Core\Generators\Tests\DelegateTestGenerator
baseNamespace: App
baseTestNamespace: Tests
testCase: Tests\TestCase
testClassFinal: true
testClassStrictTypes: false
testClassTypedProperties: true
excludedMethods:
  - __construct
  - __destruct
mergedPhpDoc:
  - author
  - copyright
  - license
  - version
phpDoc: []
phpHeaderDoc:
options:
  context: laravel
