name: CI

on:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [ 8.0 ]
        os: [ ubuntu-latest, windows-latest ]

    name: PHP${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.11.0
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer self-update
          composer install --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit -c phpunit.xml.dist

      - name: Prepare SonarCloud Scan
        run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' .coverage/clover.xml
        if: ${{ matrix.php == '8.0' && matrix.os == 'ubuntu-latest' }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        if: ${{ matrix.php == '8.0' && matrix.os == 'ubuntu-latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
